name: 'Deploy app'

on:
  push:
    branches:
      - "master"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@master

      - name: Echo
        run: echo $(date)

  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    needs: build-and-publish
    steps:
      - name: Deploy dev
        run: echo Deploy Dev...

  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    needs: [build-and-publish, deploy-dev]
    steps:
      - name: Deploy prod
        run: echo Deploy Prod...